/**
 * This file was generated by the Jeddict
 */
package com.easyData.pos.easyPos.rest.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

/**
 * @author taleb
 */
@Entity
public class MNG_USGROUP implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @OneToOne(targetEntity = MNG_PACK.class, mappedBy = "MNG_USGROUP")
    private MNG_PACK MNG_PACK;

    @OneToMany(targetEntity = MNG_USER.class)
    private List<MNG_USER> usg_users;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public MNG_PACK getMNG_PACK() {
        return this.MNG_PACK;
    }

    public void setMNG_PACK(MNG_PACK MNG_PACK) {
        this.MNG_PACK = MNG_PACK;
    }

    public List<MNG_USER> getUsg_users() {
        return this.usg_users;
    }

    public void setUsg_users(List<MNG_USER> usg_users) {
        this.usg_users = usg_users;
    }

}
