/**
 * This file was generated by the Jeddict
 */
package com.easyData.pos.easyPos.rest.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

/**
 * @author taleb
 */
@Entity
public class MNG_MENU {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @OneToOne(targetEntity = MNG_FONCTION.class)
    private MNG_FONCTION MNG_FONCTION;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public MNG_FONCTION getMNG_FONCTION() {
        return this.MNG_FONCTION;
    }

    public void setMNG_FONCTION(MNG_FONCTION MNG_FONCTION) {
        this.MNG_FONCTION = MNG_FONCTION;
    }

}
