/**
 * This file was generated by the Jeddict
 */
package com.easyData.pos.easyPos.rest.model;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * @author taleb
 */
@Entity
@Table(name = "MNG_USER_LANG")
public class MNG_PROFILE implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @OneToOne(targetEntity = MNG_USGROUP.class)
    private MNG_USGROUP MNG_USGROUP;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public MNG_USGROUP getMNG_USGROUP() {
        return this.MNG_USGROUP;
    }

    public void setMNG_USGROUP(MNG_USGROUP MNG_USGROUP) {
        this.MNG_USGROUP = MNG_USGROUP;
    }

}
