/**
 * This file was generated by the Jeddict
 */
package com.easyData.pos.easyPos.rest.model;

import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

/**
 * @author taleb
 */
@Entity
public class MNG_USGROUP {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @OneToOne(targetEntity = MNG_PROFILE.class, mappedBy = "MNG_USGROUP")
    private MNG_PROFILE MNG_PROFILE;

    @OneToMany(targetEntity = MNG_USER.class)
    private List<MNG_USER> usg_users;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public MNG_PROFILE getMNG_PROFILE() {
        return this.MNG_PROFILE;
    }

    public void setMNG_PROFILE(MNG_PROFILE MNG_PROFILE) {
        this.MNG_PROFILE = MNG_PROFILE;
    }

    public List<MNG_USER> getUsg_users() {
        return this.usg_users;
    }

    public void setUsg_users(List<MNG_USER> usg_users) {
        this.usg_users = usg_users;
    }

}
