/**
 * This file was generated by the Jeddict
 */
package com.easyData.pos.easyPos.rest.model;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * @author taleb
 */
@Entity
@Table(name = "MNG_USER_LANG")
public class MNG_REGLES implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @OneToOne(targetEntity = MNG_PROFILE.class)
    private MNG_PROFILE MNG_PROFILE;

    @OneToOne(targetEntity = MNG_FONCTION.class)
    private MNG_FONCTION MNG_FONCTION;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public MNG_PROFILE getMNG_PROFILE() {
        return this.MNG_PROFILE;
    }

    public void setMNG_PROFILE(MNG_PROFILE MNG_PROFILE) {
        this.MNG_PROFILE = MNG_PROFILE;
    }

    public MNG_FONCTION getMNG_FONCTION() {
        return this.MNG_FONCTION;
    }

    public void setMNG_FONCTION(MNG_FONCTION MNG_FONCTION) {
        this.MNG_FONCTION = MNG_FONCTION;
    }

}
