/**
 * This file was generated by the Jeddict
 */
package com.easyData.pos.easyPos.rest.model.component.v1;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import org.springframework.stereotype.Component;

/**
 * @author taleb
 */
@Component
@Entity
//
//@NamedQueries({
//    @NamedQuery(
//            name = "MNG_APPLICATION.findByUser",
//            query = " SELECT e FROM MNG_APPLICATION e "
//                    + " WHERE EXISTS ("
//                        + " SELECT a.MNG_FONCTION FROM MNG_PACK a "
//                        + " WHERE a.MNG_FONCTION MEMBER OF e.MNG_MENU.MNG_FONCTION"
//                        + "  AND a.id in ("
//                            + " SELECT s.MNG_PACK.id FROM MNG_USGROUP s "
//                            + "WHERE :user MEMBER OF s.usg_users  "
//                            + ")"
//                        + " ) "                                
//    )
//})

public class MNG_APPLICATION implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    
    @Basic
    private String app_name;
    

    @OneToOne(targetEntity = MNG_MENU.class)
    private MNG_MENU MNG_MENU;

    public MNG_APPLICATION() {
    }

    public void setApp_name(String app_name) {
        this.app_name = app_name;
    }

    public String getApp_name() {
        return app_name;
    }

    public MNG_APPLICATION(Long id, String app_name, MNG_MENU MNG_MENU) {
        this.id = id;
        this.app_name = app_name;
        this.MNG_MENU = MNG_MENU;
    }
    
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public MNG_MENU getMNG_MENU() {
        return this.MNG_MENU;
    }

    public void setMNG_MENU(MNG_MENU MNG_MENU) {
        this.MNG_MENU = MNG_MENU;
    }

}
