/**
 * This file was generated by the Jeddict
 */
package com.easyData.pos.easyPos.rest.model.component.v1;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import org.springframework.stereotype.Component;

/**
 * a supprimer dans la prochiane version 
 * @deprecated
 * @author taleb
 */
@Entity
@Component
public class MNG_FONCTION {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     *
     * @return
     */
    public Long getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

}
