/**
 * This file was generated by the Jeddict
 */
package com.easyData.pos.easyPos.rest.model.aoth;

import com.easyData.pos.easyPos.rest.model.Role;
import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import org.springframework.stereotype.Component;

/**
 * entité des niveau d acces c est une composition de Id,titre d acces et la liste des roles concerné
 * @author taleb
 */
@Entity
@Component
public class MNG_NIVEAU_ACCEE implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    
    @Column(unique = true)
    private String aclTitle;
    
    // to refactor and improve
    @ElementCollection(targetClass = Role.class,fetch = FetchType.EAGER)
    @Enumerated(value = EnumType.STRING)
    private Collection<Role> roles;

    /**
     *
     */
    public MNG_NIVEAU_ACCEE() {
    }

    /**
     * constructeur avec parametre
     * @param id id du acl
     * @param roleTitle titre du acl
     * @param roles liste des roles affecter a ce acl 
     */
    public MNG_NIVEAU_ACCEE(Long id, String roleTitle, Collection<Role> roles) {
        this.id = id;
        this.aclTitle = roleTitle;
        this.roles = roles;
    }

    /**
     *
     * @return
     */
    public Collection<Role> getRoles() {
        return roles;
    }

    /**
     *
     * @param aclTitle
     */
    public void setAclTitle(String aclTitle) {
        this.aclTitle = aclTitle;
    }

    /**
     *
     * @return
     */
    public String getAclTitle() {
        return aclTitle;
    }

    /**
     *
     * @param roles
     */
    public void setRoles(Collection<Role> roles) {
        this.roles = roles;
    }
    
    /**
     *
     * @return
     */
    public Long getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    
}
