/**
 * This file was generated by the Jeddict
 */
package com.easyData.pos.easyPos.rest.model.aoth;

import com.easyData.pos.easyPos.rest.model.Role;
import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import org.springframework.stereotype.Component;

/**
 * @author taleb
 */
@Entity
@Component
public class MNG_NIVEAU_ACCEE implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    
    @Enumerated(value = EnumType.ORDINAL)
    private Role role;

    public MNG_NIVEAU_ACCEE() {
    }

    public MNG_NIVEAU_ACCEE(Long id, Role role) {
        this.id = id;
        this.role = role;
    }
    
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    
}
