/**
 * This file was generated by the Jeddict
 */
package com.easyData.pos.easyPos.rest.model.aoth;

import com.easyData.pos.easyPos.rest.model.component.MNG_COMPOSANT;
import java.io.Serializable;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import org.springframework.stereotype.Component;

/**
 * @author taleb
 */
@Entity
@NamedQueries({
  @NamedQuery(name = "MNG_PACK.findAllByIds" , query = "SELECT e FROM MNG_PACK e WHERE e.id IN :ids ")  
})
@Component
public class MNG_PACK implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(unique = true)
    private String packName;
    
    @OneToMany(targetEntity = MNG_COMPOSANT.class)
    private List<MNG_COMPOSANT> mng_composants;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setPackName(String packName) {
        this.packName = packName;
    }

    public String getPackName() {
        return packName;
    }

    
    public List<MNG_COMPOSANT> getMng_composants() {
        return this.mng_composants;
    }

    public void setMng_composants(List<MNG_COMPOSANT> mng_composants) {
        this.mng_composants = mng_composants;
    }

}

