/**
 * This file was generated by the Jeddict
 */
package com.easyData.pos.easyPos.rest.model.aoth;

import com.easyData.pos.easyPos.rest.model.component.MNG_COMPOSANT;
import java.io.Serializable;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import org.springframework.stereotype.Component;

/**
 * Entit des pack
 * un pack se compose d un id un nom et une liste de composant (pour l instant que des applications )
 * la requete findAllByIds est une  requete qui retourne la liste des packs selon une list d id
 * les id dans jpa son generer automatiquement et garanti unique
 * ceci est un pojo simple
 * @see MNG_COMPOSANT
 * @author taleb
 */
@Entity
@NamedQueries({
  @NamedQuery(name = "MNG_PACK.findAllByIds" , query = "SELECT e FROM MNG_PACK e WHERE e.id IN :ids ")  
})
@Component
public class MNG_PACK implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(unique = true)
    private String packName;
    
    @ManyToMany(targetEntity = MNG_COMPOSANT.class)
    private List<MNG_COMPOSANT> mng_composants;

    /**
     *
     * @return
     */
    public Long getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *
     * @param packName
     */
    public void setPackName(String packName) {
        this.packName = packName;
    }

    /**
     *
     * @return
     */
    public String getPackName() {
        return packName;
    }

    /**
     *
     * @return
     */
    public List<MNG_COMPOSANT> getMng_composants() {
        return this.mng_composants;
    }

    /**
     *
     * @param mng_composants
     */
    public void setMng_composants(List<MNG_COMPOSANT> mng_composants) {
        this.mng_composants = mng_composants;
    }

}

