/**
 * This file was generated by the Jeddict
 */
package com.easyData.pos.easyPos.rest.model.aoth;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import org.springframework.stereotype.Component;

/**
 * l entité programme est le reflet d une table qui va stoqué la liste des programme
 * au futur on compte delegé certain traitement a des processus batch pour une traçabilité chaque processus batch ou un autre utilitaire va devoir etre inscrit 
 * on a besoin de son id et son nom
 * 
 * @author taleb
 */
@Entity
@Component
public class MNG_PROGRAM implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String programName;
    
    /**
     *
     * @return
     */
    public Long getId() {
        return this.id;
    }
    
    /**
     *
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *
     */
    public MNG_PROGRAM() {
    }

    /**
     *
     * @param id
     * @param programName
     */
    public MNG_PROGRAM(Long id, String programName) {
        this.id = id;
        this.programName = programName;
    }

    /**
     *
     * @return
     */
    public String getProgramName() {
        return programName;
    }

    /**
     *
     * @param programName
     */
    public void setProgramName(String programName) {
        this.programName = programName;
    }

    
    
}
